# General sensor definitions.
dataset: Lunarsim
ncam: 2

camera_0:
  topic: /rosbag/camera_left/raw
  # Sensor extrinsics wrt. the body-frame.
  T_BS:
    cols: 4
    rows: 4
    # no rotation, no translation
    data: [1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

  # Camera specific definitions.
  rate_hz: 4
  resolution: [1280, 720]
  projection_model: pinhole
  intrinsics: [504.76190185546875, 502.1052551269531, 640.0, 360.0] #fu, fv, cu, cv
  distortion_model: radial-tangential
  distortion_coefficients: [0.0, 0.0, 0.0, 0.0]

camera_1:
  topic: /rosbag/camera_right/raw
  # Sensor extrinsics wrt. the body-frame.
  T_BS:
    cols: 4
    rows: 4
    data: [1.0, 0.0, 0.0, 0.16,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

  # Camera specific definitions.
  rate_hz: 4
  resolution: [1280, 720]
  projection_model: pinhole
  intrinsics: [504.76190185546875, 502.1052551269531, 640.0, 360.0] #fu, fv, cu, cv
  distortion_model: radial-tangential
  distortion_coefficients: [0.0, 0.0, 0.0, 0.0]

imu:
  topic: /lunarsim/imu
  T_BS:
    cols: 4
    rows: 4
    data: [1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0]
  rate_hz: 100

  # inertial sensor noise model parameters (static)
  gyroscope_noise_density: 0.01     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk: 0.001       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  accelerometer_noise_density: 0.1  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 0.0001    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  
